---
- name: 'Gater datastore facts on vmware cluster'
  #run MODULE against localhost
  hosts: localhost
  vars:
    datacenter_name: "NTXMD"
    result_JSON: 'false'
 
  tasks:
  - name: "Get Cluster Facts"
    vmware_datastore_facts:
      #datacenter_name: 'NTXMD'
      cluster: MD_CL11_GEN_POP_NONPROD
      validate_certs: no
    register: clusterFacts
  - set_fact: 
      factsToJSON: "{{clusterFacts | to_json}}"
      #datastoreName: "{{clusterFacts.datastores[0].datastore_cluster}}"
      #tags: "{{clusterFacts.datastores[0].datastore_cluster}}"
  - name: "Cluster Facts to JSON"
    debug: 
      msg: "{{factsToJSON}}"
  #- name: "clusterFacts full"
  #  debug: var=clusterFacts
  #- name: "clusterFacts"
  #  debug: 
  #    msg: "{{datastoreName}}"
