---
- name: 'Gater datastore facts on vmware cluster'
  #run MODULE against localhost
  hosts: localhost
  vars:
    datacenter_name: "MSLAB"
    vm_name: "{{ VM_NAME }}"
    result_JSON: 'false'
 
  tasks:
  - name: "Get Datastore Facts"
    vmware_datastore_facts:
      #datacenter_name: 'MSLAB'
      cluster: Mgmt
      validate_certs: no
    register: clusterFacts
  - name: "Facts to JSON"
    debug: 
      msg: "{{clusterFacts| to_json}}"
