#credentials test
---
- name: "credentials test - David Smith"
  hosts: all
  tasks:
  # Take survey Vars dict and create list of concatenated key:value pairs
  - name: "Become "
    win_whoami:
      become: yes
    register: result
  - debug:
    var: result   
