#deploy VM 1st try
---
- name: "Deploy VM Try 01 - David Smith"
  hosts: all
  vars:
    vcenterVars:
      datacenterName: NTXMD
      notes: Created by Ansible      
    surveyVars:
      vmName: BSWANSBVMT01
      os: "Windows"
      application: "Gen-pop"
      tier: "1"
      environment: "Non-Prod"
      location: "Temple"
      SQL: "no"
    networkName: "VM Network"
    templateName: VRATD2016PTC
    clusterName: MD_CL11_GEN_POP_NONPROD
    group: group1
    
  tasks:
  # Take survey Vars dict and create list of concatenated key:value pairs
  - name: "Set Fact result_list"
    set_fact: 
      result_item: '{{ item.key }}:{{ item.value }}'
    with_dict:
      - '{{ surveyVars }}'
    register: result_list
  - name: "Build comma separated string"
    set_fact:
    # Build comma separated string of the key:value pairs to send to pshell powercli to make cluster
    # placement decision based on cluster tags    
      csString: '{{ result_list.results | map(attribute="ansible_facts.result_item") | join(",") }}'
  - name: "Sending CS String"
    debug:
      var: csString
    #username: '{{ vcenter_username }}'
    #password: '{{ vcenter_password }}' 
  # send to pshell
  - name: "Run script 'ansible_selectClusterBasedOnSurvey.ps1'"
    win_shell: D:\scripts\vSphere\ansible_selectClusterBasedOnSurvey.ps1 -ansibleString csString -userName '{{ lookup("env", "VMWARE_USER") }}' -password '{{ lookup("env", "VMWARE_PASSWORD") }}'
    register: pshellResult
  
  - name: "set fact pshell"
    set_fact: 
      destinationCluster: "{{ pshellResult.stdout }}"
  
  - name: "the results are"
    debug: var=pshellResult
