#powershell variables test
---
- name: Set Environment and Variables
  hosts: all
  vars: 
    #vars from survey have to be root level vars ###########
    vmName: ""
    OS: ""
    OS_Version: ""
    Application: ""
    Tier: ""
    Environment: ""
    Location: ""
    SQL: ""
    num_CPU: ""
    GB_RAM: ""
    #END vars from survey ##########
    #set surveyVars to vars from survey to be able to pass to powershell ie JSON 
    surveyVars:    
      a_vmName: "{{vmName}}"
      a_OS: "{{OS}}"
      a_OS_Version: "{{OS_Version}}"
      a_Application: "{{Application}}"
      a_Tier: "{{Tier}}"
      a_Environment: "{{Environment}}"
      a_Location: "{{Location}}"
      a_SQL: "{{SQL}}"
      a_num_CPU: "{{num_CPU}}"
      a_GB_RAM: "{{GB_RAM}}"
      a_vcenter_CL_availableSubnets: ""
      #END set surveyVars #########

  vars_files:
  #- vars/surveyVars.yml
  - vars/vars.yml
 
  tasks:
  - name: "------ surveyVars are --------------------"
    debug: var=surveyVars
  - meta: end_play
 ########## GET CLUSTER BASED ON SURVEY
  - name: "set pshellScriptAction to getClusterBasedOnSurvey"
    set_fact:
      pshellScriptAction: getClusterBasedOnSurvey #not sent as JSON with unicode

  - name: "Run script 'ansible_deployVM.ps1'"
    win_shell: D:\scripts\vSphere\ansible_deployVM.ps1 -pshellScriptAction "{{pshellScriptAction}}" -surveyVars "{{surveyVars }}" -userName '{{ ansible_user }}' -password '{{ ansible_password }}' -vm "{{vm }}" -networkAdapter "{{networkAdapter}}" -disk "{{disk}}" 
    register: result
  
  - name: "Process win_shell output"
    set_fact:
      vm: "{{ result.stdout | from_json }}"
  
  - name: "The VM variable including Cluster Placement results are"
    debug: var=vm
  #- meta: end_play
 
  ######### GET NETWORKS FOR CLUSTER
  - name: "set pshellScriptAction to getNetworksForCluster"
    set_fact:
      pshellScriptAction: getNetworksForCluster   #not sent as JSON with unicode
  - name: "Run script 'ansible_deployVM.ps1' and GET NETWORKS FOR CLUSTER"
    win_shell: D:\scripts\vSphere\ansible_deployVM.ps1 -pshellScriptAction "{{pshellScriptAction}}" -surveyVars "{{surveyVars }}" -userName '{{ ansible_user }}' -password '{{ ansible_password }}' -vm "{{vm }}" -networkAdapter "{{networkAdapter}}" -disk "{{disk}}" 
    register: result
  
  - name: 
    set_fact:
      surveyVars: "{{ result.stdout | from_json }}"
  
  - name: "The surveyVars varialbe inclding networks available"
    debug: var=surveyVars
  #- meta: end_play

  ######### GET DATASTORE FOR CLUSTER
  - name: "set pshellScriptAction to getDatastoreForCluster"
    set_fact:
      pshellScriptAction: getDatastoreForCluster   #not sent as JSON with unicode
  - name: "Run script 'ansible_deployVM.ps1' and GET NETWORKS FOR CLUSTER"
    win_shell: D:\scripts\vSphere\ansible_deployVM.ps1 -pshellScriptAction "{{pshellScriptAction}}" -surveyVars "{{surveyVars }}" -userName '{{ ansible_user }}' -password '{{ ansible_password }}' -vm "{{vm }}" -networkAdapter "{{networkAdapter}}" -disk "{{disk}}" 
    register: result
  
  - name: "Process win_shell output"
    set_fact:
      vm: "{{ result.stdout | from_json }}"
  
  - name: "The vm variable with attached adapter"
    debug: var=vm
  #- meta: end_play
  
  ######## GET IP RESERVATION FOR NETWORK ADAPTER
  - name: "set pshellScriptAction to getIPReservationForNetworkAdapter"
    set_fact:
      pshellScriptAction: getIPReservationForNetworkAdapter      #not sent as JSON with unicode
  - name: "Run script 'ansible_deployVM.ps1'"
    win_shell: D:\scripts\vSphere\ansible_deployVM.ps1 -pshellScriptAction "{{pshellScriptAction}}" -surveyVars "{{surveyVars }}" -userName '{{ ansible_user }}' -password '{{ ansible_password }}' -vm "{{vm }}" -networkAdapter "{{networkAdapter}}" -disk "{{disk}}" 
    register: result
  
  - name: "Process win_shell output"
    set_fact:
      vm: "{{ result.stdout | from_json }}"
  
  - name: "The vm variable with attached adapter"
    debug: var=vm
  #- meta: end_play   
   ######## 
  - name: "set pshellScriptAction to getVMTemplate"
    set_fact:
      pshellScriptAction: getVMTemplatesForCluster      
  - name: "Run script 'ansible_deployVM.ps1'"
    win_shell: D:\scripts\vSphere\ansible_deployVM.ps1 -pshellScriptAction "{{pshellScriptAction}}" -surveyVars "{{surveyVars }}" -userName '{{ ansible_user }}' -password '{{ ansible_password }}' -vm "{{vm }}" -networkAdapter "{{networkAdapter}}" -disk "{{disk}}" 
    register: result
  
  - name: "Process win_shell output"
    set_fact:
      vm: "{{ result.stdout | from_json }}"
  
  - name: "The vm variable with attached template is"
    debug: var=vm
   ######## 
  - name: "set pshellScriptAction to getDatacenterForVM "
    set_fact:
      pshellScriptAction: getDatacenterForVM      
  - name: "Run script 'ansible_deployVM.ps1'"
    win_shell: D:\scripts\vSphere\ansible_deployVM.ps1 -pshellScriptAction "{{pshellScriptAction}}" -surveyVars "{{surveyVars }}" -userName '{{ ansible_user }}' -password '{{ ansible_password }}' -vm "{{vm }}" -networkAdapter "{{networkAdapter}}" -disk "{{disk}}" 
    register: result
  

  - name: "Process win_shell output"
    set_fact:
      vm: "{{ result.stdout | from_json }}"
  
  - name: "The vm variable with attached Datacenter is"
    debug: var=vm
  #########

#  - name: Create a virtual machine on given ESXi hostname
#    vmware_guest:
