---
# vim: set ft=ansible et ts=2 sw=2:
#
# Create a new VM from a template using the new vmware_guest mod
- name: VM from_template
  hosts: localhost
  vars:
    datacenter: MSLAB
    esxhost: mslab37.bhcs.pvt
    datastore: Mgmt_005FA_1
    network: "VM Network"
    vmname: ansbt01
    vmtemplate: DGSANSBTPL01
    vmcluster: Mgmt
    vmFolder: "/"
    notes: Created by Ansible
    group: group1
    guestID: windows9Server-64
    dumpfacts: False
  tasks:
    - name: Find Guest's Folder using name
      vmware_guest_find:
        validate_certs: no
        name: DGSANSBTST01
      delegate_to: localhost
      register: vm_folder
    - debug:
        var: vm_folder
