#getCluster
---
  #run MODULE against localhost
  hosts: localhost
 
  tasks:
    - name: 'gater VM facts to determine if power action needed'
      vmware_cluster_info:
        datacenter: NTX
        validate_certs: no
      register: cluster_info
    - debug:
      var: cluster_info