#getCluster
---
- hosts: all

  tasks:
  - name: 'gater VM facts to determine if power action needed'
    vmware_cluster_facts:
      datacenter: NTX
      validate_certs: no
    register: cluster_info
  - debug:
      var: cluster_info