#getCluster
---
- hosts: all

  tasks:
  - name: Cluster Info
    vmware_cluster_facts:
      datacenter: NTXMD
      validate_certs: no
      cluster_name: MD_CL11_GEN_POP_NONPROD
    register: cluster_info
  - debug:
      var: cluster_info


  - name: Gather vmware host facts from vCenter with tag information
    vmware_host_facts:
      esxi_hostname: ntxmdh154.bhcs.pvt
      show_tag: True
    register: host_facts_tag
  - debug:
      var: host_facts_tag    