#getCluster
---
- hosts: all

  tasks:
  - name: 'gater VM facts to determine if power action needed'
    vmware_cluster_facts:
      datacenter: NTXMD
      validate_certs: no
      cluster_name: MD_CL11_GEN_POP_NONPROD
    register: cluster_info
  - debug:
      var: cluster_info