#powershell variables test
---
- name: Variables Test
  hosts: all
  vars:

    
    vm:
      annotation: This is a VM
      cdrom:
        type: client
        iso_path: ''
        controller_type: ''
        state: ''
      cluster: ''

  tasks:
  - name: Process win_shell output
    set_fact:
      vmToJSON: "{{ vm | to_json }}" 

  - name: 'THE VM TO JSON'
    debug:
      msg: "{{ vmToJSON }}"     

  - name: "Run script '.ps1'"
    win_shell: D:\scripts\outputValues.ps1 -vm "{{vmToJSON}}" #  -vm "{{vm}}" #-userName '{{ ansible_user }}' -password '{{ ansible_password }}'
    # "{{ surveyVars | list | join("\", \"") }}"
    register: result
  - name: Process win_shell output
    set_fact:
      fullResult: "{{ result.stdout | from_json }}"
  
  - name: Return Values
    debug:
      msg: "{{ fullResult }}"

