#powershell variables test
---
- name: Check winrm
  hosts: all
    
  tasks:
  
  - name: Check winrm is Installed and get status
    win_service:
     name: winRM
    register: winrmstatus
  - debug:
      msg: "{{ winrmstatus }}" 