#read/write JSON
---
- hosts: localhost
#dest="{{ playbook_dir }}/testFile.yml"
  vars:
    topLevelVars:
      serverName: 'BSWDGSANSBT02'
      os: 'Windows'
      osVersion: 'Windows 2016'
  tasks:
  #write vars
  - name: 'write vars to file'
    copy: 
      content: "{{ topLevelVars | to_nice_json }}" 
      dest: "{{ playbook_dir }}/testFile1.yml" 
  #load vars from file
  - name: 'Load vars from file'
    include_vars: ##### here #######
      file: "{{ playbook_dir }}/testFile1.yml"
      name: imported_vars
  #show var var values 
  - name: 'Show Loaded Vars'
    debug: var=imported_vars
  #change value of existing vars
  #- name: 'change serverName'
  #  set_fact:
  #    topLevelVars: "{{ "
  #  set_fact:
  #    topLevelVars: '{ "serverName": wasBSWDGSANSBT02, "os": LEENUX }' 
  #append to var
  - name: 'append more key/values'
    set_fact:
      topLevelVars: "{{ topLevelVars | default([]) | combine({ 'hello': 'world' }) }}"
#write vars
  - name: 'write vars to file again'
    copy: 
      content: "{{ topLevelVars | to_nice_json }}" 
      dest: "{{ playbook_dir }}/testFile1.yml" 
  #load vars from file
  - name: 'load var from file again'
    include_vars:
      file: "{{ playbook_dir }}/testFile1.yml"
      name: imported_varsChanged
  #show var var values 
  - name: 'dump changed vars'
    debug: var=imported_varsChanged
