#deploy VM 1st try
---
- name: "Deploy VM Try 01 - David Smith"
  hosts: all
  vars:
    vcenterVars:
      datacenterName: NTXMD
      notes: Created by Ansible      
    surveyVars:
      vmName: BSWANSBVMT01
      os: "Windows_Server_2016"
      application: "Gen-pop"
      tier: "1"
      environment: "Non-Prod"
      location: "Main_Street"
      SQL: "no"
    networkName: "VM Network"
    templateName: VRATD2016PTC
    clusterName: MD_CL11_GEN_POP_NONPROD
    group: group1
    
    tasks:
    # Take survey Vars dict and create list of concatenated key:value pairs
    - set_fact: 
        result_item: '{{ item.key }}:{{ item.value }}'
      with_dict:
        - '{{ surveyVars }}'
      register: result_list

    - set_fact:
      # Build comma separated string of the key:value pairs to send to pshell powercli to make cluster
      # placement decision based on cluster tags    
        result: '{{ result_list.results | map(attribute="ansible_facts.result_item") | join(",") }}'
    # send to pshell
    - name: "Run script 'outputValues.ps1'"
      win_shell: D:\scripts\outputValues.ps1 -value01 "{{ result }}"
    
    - debug:
        var: result
