#variables test
- hosts: all
  connection: local
  vars:
    surveyVars:
      vmName: BSWANSBVMT01
      os: "Windows_Server_2016"
      application: "Gen-pop"
      tier: "1"
      environment: "Non-Prod"
      location: "Main_Street"
      SQL: "no"
  tasks:
    - set_fact:
        #result_item: '{{ item.name }}-{{ item.port }}'
        result_item: '{{ item.key }}-{{ item.value }}'
      with_dict:
        - '{{ surveyVars }}'
      register: result_list

    - set_fact:
        result: '{{ result_list.results | map(attribute="ansible_facts.result_item") | join(",") }}'

    - debug:
        var: result
