#Variables Test
---
- name: "Variables Test"
  hosts: all
  vars:
        #JSON example
    surveyVars:
      vmName: "BSWANSBVMT01"
      os: "Windows_Server_2016"
      application: "Gen-pop"
      tier: "1"
      environment: "Non-Prod"
      location: "Main_Street"
      SQL: "no"
  tasks:
  # Some script to dump vars to pshell, which writes to txt file and returns some stuff
  # as a test of what we are getting back and forth from here to powershell and back
  - name: "Run script "
  #  #Send dicts to powershell, they show up with u'*'. Powershell converts to json, 
  #  # then to pshell object for . notation, sets some values, sends back pure JSON
    win_shell: D:\scripts\outputValues.ps1 -surveyVars "{{surveyVars}}" #-mrjson "{{mrjson}}" #-userName '{{ ansible_user }}' -password '{{ ansible_password }}'
    register: result
  - name: Process win_shell output
    set_fact:
      result: "{{ result.stdout | from_json }}"
  - name: Return Values
    debug:
      msg: "{{ result }}"
