#Variables Test
---
- name: "Variables Test"
  hosts: all
  vars:
    #JSON example
    {
    "a_outer": {"an_int": 43,
    "a_string": "some string",
    "a_list": ["element_1","element_2"],
    "a_dict": {"key1": "string-data",
               "key2": 56}}
    }
    #surveyVars:
    #  vmName: BSWANSBVMT01
    #  os: "Windows_Server_2016"
    #  application: "Gen-pop"
    #  tier: "1"
    #  environment: "Non-Prod"
    #  location: "Main_Street"
    #  SQL: "no"
  tasks:
  # Some script to dump vars to pshell, which writes to txt file and returns some stuff
  # as a test of what we are getting back and forth from here to powershell and back
  - name: "Run script 'outputValues.ps1'"
  #  #Send dicts to powershell, they show up with u'*'. Powershell converts to json, 
  #  # then to pshell object for . notation, sets some values, sends back pure JSON
    win_shell: D:\scripts\outputValues.ps1 -mrjson "{{a_outer}}" #-surveyVars "{{surveyVars }}" #-userName '{{ ansible_user }}' -password '{{ ansible_password }}'
    register: result
  - name: Process win_shell output
    set_fact:
      result: "{{ result.stdout | from_json }}"
  - name: Return Values
    debug:
      msg: "{{ result }}"
