- name: Gather some facts from a guest using the vSphere API output schema
  hosts: localhost
  vars:
    datacenter_name: "MSLAB"
    vm_name: "DGSANSBTST01"
  tasks:
    - name: Gater VM Facts
      vmware_guest_facts:
        #hostname: "{{ vcenter_hostname }}"
        #username: "{{ vcenter_username }}"
        #password: "{{ vcenter_password }}"
        validate_certs: no
        datacenter: "MSLAB"
        folder: "/MSLAB/Ansible" 
        name: "DGSANSBTST01"
        schema: "vsphere"
        properties: ["config.hardware.memoryMB", "guest.disk", "overallStatus"]
        register: facts
    - debug: 
        msg: "{{ facts }}"
