- name: Gather some facts from a guest using the vSphere API output schema
  hosts: localhost
  vars:
    datacenter_name: "MSLAB"
    vm_name: "DGSANSBTST01"
  tasks:
    - name: Gater VM Facts
      vmware_guest_facts:
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        schema: "vsphere"
        properties: ["guest.hostName", "guest.toolsVersionStatus","summary.runtime.powerState"]
      register: facts
    - debug: 
        msg: "{{ ansible_facts["guest"]["hostName"] }}"
