---
# vim: set ft=ansible et ts=2 sw=2:
#
# Create a new VM from a template using the new vmware_guest mod
- name: VM from_template
  hosts: localhost
  vars:
    datacenter: MSLAB
    esxhost: mslab37.bhcs.pvt
    datastore: Mgmt_005FA_1
    network: "VM Network"
    vmname: ansbt01
    vmtemplate: DGSANSBTPL01
    vmcluster: Mgmt
    vmFolder: "/MSLAB/vm/Ansible"
    notes: Created by Ansible
    group: group1
    guestID: windows9Server-64
    dumpfacts: False
  tasks:
    - name: Create VM from template
      vmware_guest:
        validate_certs: False
        folder: "{{ vmFolder }}"
        datacenter: "{{ datacenter }}"
        name: "{{ vmname }}"
        template: "{{ vmtemplate }}"
        guest_id: "{{ guestID }}"
        disk:
        - size_gb: 60
          type: thin
          datastore: "{{ datastore }}"
        networks:
        - name: "{{ network }}"
          device_type: vmxnet3 
          type: dhcp
        hardware:
          memory_mb: 4096
          num_cpus: 2
        wait_for_ip_address: False
        state: present
      register: newvm

#    - debug:
#        msg: "{{ newvm.instance.ipv4 }} {{ name }} "
