#patch vm
---
- name: "Get VM Template"
  hosts: localhost
  vars:
    datacenterName: NTXMD
    notes: Created by Ansible 
    vmTemplateName: BSWVMTPL2012R2
  
    
  tasks:
  # Take survey Vars dict and create list of concatenated key:value pairs
    - name: Get virtual machine custom attributes
      vmware_guest_facts:
        validate_certs: no
        datacenter: "{{ datacenterName }}"
        name: "{{ vmTemplateName }}"
        schema: "vsphere"
      register: facts

    #- name: Get key/value pairs for ansible_VM_*
    #  no_log: True
    #  properties: 
    #  with_dict: " {{facts[0]]}} "
    #  #when: "item.value.name.startswith('ansible_VM_')"



    - name: "VM Attributes are - "
      set_fact: 
        ansibleFields: "{{ facts.instance.availableField | map('json_query','{name:name,key:key}') | list}}"
      debug:  
        msg: "{{ ansibleFields[0] }}"