#patch vm
---
- name: "Get VM Template"
  hosts: all
  vars:
    datacenterName: NTXMD
    notes: Created by Ansible 
    vmTemplateName: BSWVMTPL2012R2
  
    
  tasks:
  # Take survey Vars dict and create list of concatenated key:value pairs
  - name: Add virtual machine custom attributes
    vmware_guest_custom_attributes:
      validate_certs: no
      name: "{{vmTemplateName}}"
    delegate_to: localhost
    register: attributes
  - name: "VM Attributes are - "
    debug:
      var: attributes