#patch vm
---
- name: "Get VM Template"
  hosts: localhost
  vars:
    datacenterName: NTXMD
    notes: Created by Ansible 
    vmTemplateName: BSWVMTPL2012R2
  
    
  tasks:
  # Take survey Vars dict and create list of concatenated key:value pairs
    - name: Get virtual machine custom attributes
      vmware_guest_facts:
        validate_certs: no
        datacenter: "{{ datacenterName }}"
        name: "{{ vmTemplateName }}"
        schema: "vsphere"
      register: facts

    - name: "Show -vmid variable"
      debug: 
        msg: "{{facts.instance._vimid}}"
       
    - name: "Show availableField variable"
      debug: 
        msg: "{{facts.instance.availableField}}"
    
    - name: "Display all server names"
      debug:
        var: item
      loop: "{{ facts | json_query('instance.availableField[*].name') }}"
