---
- name: Set powerstate of a virtual machine to poweroff or on
  #run MODULE against localhost
  hosts: localhost
  vars:
    datacenter_name: "MSLAB"
    vm_name: "{{ VM_NAME }}"
  
  tasks:
    - name: gater VM facts to determine if power action needed
      vmware_guest_facts:
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ VM_NAME }}"
        schema: "vsphere"
        properties: ["summary.runtime.powerState"]
      register: vmGuestFacts
      vars:
        var_currentPowerState: "{{ vmGuestFacts['instance']['summary']['runtime']['powerState'] }}"

    - name: Power On
      vars:
        var_currentPowerState: "{{ vmGuestFacts['instance']['summary']['runtime']['powerState'] }}"
      vmware_guest_powerstate:
        validate_certs: no
        folder: "/MSLAB/Ansible"
        name: "{{ VM_NAME }}"
        state: powered-on
      when: DESIRED_VM_POWER_STATE == 'On' and var_currentPowerState == 'poweredOff'
 
    - name: Power Off
      vmware_guest_powerstate:
        validate_certs: no
        folder: "/MSLAB/Ansible"
        name: "{{ VM_NAME }}"
        state: powered-off
      when: DESIRED_VM_POWER_STATE == 'Off' and var_currentPowerState == 'poweredOn'
