---
- name: Set powerstate of a virtual machine to poweroff or on
  #run MODULE against localhost
  hosts: localhost
  vars:
    datacenter_name: "MSLAB"
    vm_name: "{{ VM_NAME }}"
  
  tasks:
    - name: gater VM facts to determine if power action needed
      vmware_guest_facts:
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ VM_NAME }}"
        schema: "vsphere"
        properties: ["summary.runtime.powerState"]
      register: vmGuestFacts
      msg: VM Power State is "{{ vmGuestFacts['instance']['summary']['runtime']['powerState'] }}"

    - name: Power On
      vmware_guest_powerstate:
        validate_certs: no
        name: "{{ VM_NAME }}"
        state: powered-on
      debug: 
        msg: VM Was powered ON
      when: DESIRED_VM_POWER_STATE == 'On' and "{{ vmGuestFacts['instance']['summary']['runtime']['powerState'] == 'poweredOff' }}"
 
    - name: Power Off
      vmware_guest_powerstate:
        validate_certs: no
        name: "{{ VM_NAME }}"
        state: powered-off
      debug: 
        msg: VM Was powered OFF
      when: DESIRED_VM_POWER_STATE == 'Off' and "{{ vmGuestFacts['instance']['summary']['runtime']['powerState'] == 'poweredOn' }}"

    - debug:
        msg: System DESIRED_VM_POWER_STATE has value {{ DESIRED_VM_POWER_STATE }}
    
    - debug:
        msg: System was on   
      when: "{{ vmGuestFacts['instance']['summary']['runtime']['powerState'] == 'poweredOn' }}"
    
    - debug:
        msg: System was Off   
      when: "{{ vmGuestFacts['instance']['summary']['runtime']['powerState'] == 'poweredOff' }}"  
