---
- name: Set powerstate of a virtual machine to poweroff or on
  #run MODULE against localhost
  hosts: localhost
  vars:
    datacenter_name: "MSLAB"
    vm_name: "{{ VM_NAME }}"
 
  tasks:
    - name: gater VM facts to determine if power action needed
      vmware_guest_facts:
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ VM_NAME }}"
        schema: "vsphere"
        properties: ["summary.runtime.powerState"]
      register: facts
    #use set_fact to set a variable outside of vars:
    - set_fact: fPowerState=facts.instance.summary.runtime.powerState

    - name: Power On
      vmware_guest_powerstate:
        validate_certs: no
        name: "{{ VM_NAME }}"
        state: powered-on
      register: fact_powerOn
      when: DESIRED_VM_POWER_STATE == 'On' and fPowerState == 'poweredOff'
 
    - name: Power Off
      vmware_guest_powerstate:
        validate_certs: no
        name: "{{ VM_NAME }}"
        state: powered-off
      register: fact_powerOff
      when: DESIRED_VM_POWER_STATE == 'Off' and fPowerState == 'poweredOn'
    
    - debug: var=fact_powerOn
      when: fact_powerOn

    - debug: var=fact_powerOff
      when: fact_powerOff
