---
- name: Set powerstate of a virtual machine to poweroff or on
  #run MODULE against localhost
  hosts: localhost
  vars:
    datacenter_name: "MSLAB"
    vm_name: "{{ VM_NAME }}"
 
  tasks:
    - name: gater VM facts to determine if power action needed
      vmware_guest_facts:
        validate_certs: no
        datacenter: "{{ datacenter_name }}"
        name: "{{ VM_NAME }}"
        schema: "vsphere"
        properties: ["summary.runtime.powerState"]
      register: facts
      #currentPowerState: facts.instance.summary.runtime.powerState
      
    - name: Power On
      vmware_guest_powerstate:
        validate_certs: no
        name: "{{ VM_NAME }}"
        state: powered-on
      retister: powerOn
      when: DESIRED_VM_POWER_STATE == 'On' and facts.instance.summary.runtime.powerState == 'poweredOff'
 
    - name: Power Off
      vmware_guest_powerstate:
        validate_certs: no
        name: "{{ VM_NAME }}"
        state: powered-off
      register: powerOff
      when: DESIRED_VM_POWER_STATE == 'Off' and facts.instance.summary.runtime.powerState == 'poweredOn'
    
    - debug: var=powerOn
    - debut: var=powerOff
