#winpshell test
---
- name: Check winrm
  hosts: all
  vars:
    var1: 'abc'
    var2: 'def'
    varArray:
      val1: 'element1'
      val2: 'element2'
  tasks:
  #this works
  #- name: "Run script 'outputValues.ps1'"
  #  win_shell: C:\scripts\outputValues.ps1 -value01 "{{ var1  }}"
  
  - name: "Run script 'outputValues.ps1'"
    win_shell: D:\scripts\outputValues.ps1 -value01 "{{ vars | to_json}}""
