#winpshell test
---
- name: Check winrm
  hosts: all
  vars:
    var1: 'abc'
    var2: 'def'
    varArray:
      val1: 'element1'
      val2: 'element2'
    listVars:
      - 'one'
      - 'two'
      - 'three'
  tasks:
  #- name: "Run script 'outputValues.ps1'"
  #  win_shell: D:\scripts\outputValues.ps1 -value01 "{{ varArray | join(',') }}" #sends keys var1,var2 and NOT values
  #- name: "Run script 'outputValues.ps1'"
  #  win_shell: D:\scripts\outputValues.ps1 -value01 "{{ listVars | join(',') }}" #sends LIST one,two,three  

  - name: debug dictionary
    debug: msg="{{ varArray | list }}"
    #with_items: "{{ varArray | list }}"
