#winpshell test
---
- name: Check winrm
  hosts: all
  vars:
      var1: 'varOne'
      var2: 'varTwo'
      var3: 'varThree'  
  tasks:
  
  - name: "Run script 'outputValues.ps1'"
    win_shell: C:\scripts\outputValues.ps1 -value01 "{{ var1 }}"
