---
- name: Check winrm
  hosts: all
    
  tasks:
  
  - name: Check winrm is Installed
    win_service:
     name: winRM
    register: winrmstatus
  - debug:
      msg: "{{ winrmstatus.name }}" 
  
  - name: Save the result of 'whoami' in 'whoami_out'
    win_command: whoami
    register: whoami_out

  #- name: Run command that only runs if folder exists and runs from a specific folder
  #  win_command: wbadmin -backupTarget:C:\backup\
  #  args:
  #    chdir: C:\somedir\
  #    creates: C:\backup\

  - name: Run an executable and send data to the stdin for the executable
    win_command: powershell.exe -
    args:
      stdin: Write-Host test
    register: result
  - debug:
      msg: "{{ result }}" 
